# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677097255ef72eda5efd5ab3da3d65de96ae1a3410b3917e0d7dc00ef1ac0b8298bd550f4970a6b6246dc6984ff0d59a7fc628fcbd56db1391e7f4aa94365e3d

test:
  secret_key_base: d5b2a6a531a55054a67b1e26489f953bdf0a1d408c8aa36fbaf2cc776de40b884b0c04996e3ed469fe36b373030955333044dbfff708455d5d4988f9025d97e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
